In [3]:
1+1 #더하기

2

In [5]:
123e-5

0.00123

In [8]:
a = "\"python\" is awesome. \n\tHello Python"
print(a)

"python" is awesome. 
	Hello Python


In [9]:
'abc'
"abc"
'''abc'''
"""abc"""

'abc'

In [11]:
print('abc')
print("abc")
print('''abc''')
print("""abc""")

abc
abc
abc
abc


In [12]:
# 'it's mine' 
"it's mine"
'it\'s mine'
'''it's mine'''

"it's mine"

In [13]:
tx = "Hello!"

In [14]:
print(tx[0])
print(tx[3])
print(tx[0:4])
print(tx[-1])
print(tx[-3])
print(tx[2:])
print(tx[:2])

H
l
Hell
!
l
llo!
He


In [15]:
2**2

4

In [16]:
(1+0.01)**100

2.7048138294215285

In [17]:
(1-0.01)**100

0.3660323412732292

In [18]:
5/3

1.6666666666666667

In [19]:
5%3 #나머지

2

In [20]:
5//3 #몫

1

In [21]:
print([1,2,3])
print([1,2,["a", "b", "c"]])

[1, 2, 3]
[1, 2, ['a', 'b', 'c']]


In [22]:
aa = [1,2,3]
type(aa)

list

In [23]:
aa = [1,2,3]
bb = [4,5,6]
print(aa+bb)
print(aa * 2)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]


In [24]:
aa = [1,2,3]
print(aa[0])
print(aa[1:3])
print(aa[1:])
print(aa[:2])

1
[2, 3]
[2, 3]
[1, 2]


In [25]:
bb = [1,2,["a", "b", "c"]]
print(bb[0])
print(bb[2])
print(bb[2][0])
print(bb[2][1:3])

1
['a', 'b', 'c']
a
['b', 'c']


In [29]:
aa = [1,2,3]
aa[0]=55
print(aa)

[55, 2, 3]


In [27]:
gg = [1,2,3]
gg.extend(["a", "b"])
gg

[1, 2, 3, 'a', 'b']

In [28]:
gg + ["a", "b"]

[1, 2, 3, 'a', 'b', 'a', 'b']

In [30]:
mm = [1,2,3]
mm.index(1)

0

In [31]:
mm.index(2)

1

In [32]:
mm.index(5)

ValueError: 5 is not in list

In [33]:
kk = [100,200,300]
kk.index(200)

1

In [34]:
print((1,2,3))
print(1,2,[5,6,7])

(1, 2, 3)
1 2 [5, 6, 7]


In [35]:
aa = (1,2, [5,6,7])
aa[2][2] = 2
print(aa)

(1, 2, [5, 6, 2])


In [36]:
aa = (1,2,3)
type(aa)

tuple

In [37]:
tp1 = (1)
type(tp1)

int

In [38]:
tp2 = (1,)
type(tp2)

tuple

In [39]:
aa = (1,2,4,6)
aa[2] = 123
aa

TypeError: 'tuple' object does not support item assignment

In [40]:
dic = {"k1":1, "k2": "aa", "k3": [1,2,3]}
dic

{'k1': 1, 'k2': 'aa', 'k3': [1, 2, 3]}

In [41]:
dic[2]

KeyError: 2

In [44]:
dic["k3"]

[1, 2, 3]

In [45]:
aa = "asdf"
aa.upper()

'ASDF'

In [46]:
num = "010-1234-5678"
num.split("-")

['010', '1234', '5678']

In [47]:
" + ".join(["x1", "x2", "x3"])

'x1 + x2 + x3'

In [48]:
True

True

In [49]:
False

False

In [50]:
True + False

1

In [51]:
sum([True, True, False ])

2

In [52]:
4 > 2

True

In [53]:
2 > 4

False

In [54]:
if True:
    print(123)

123


In [55]:
if False:
    print(123)

In [56]:
if 3 > 0:
    print(123)

123


In [57]:
value = 100
if value >= 50:
    print("up")

up


In [59]:
valle = 100
if value <= 50:
    print("up")
else:
    print("down")

down


In [63]:
level = ["A","B","C","D","f" ]
mine = "C"
if mine in level [:1]:
    print("pass")
elif mine == level[2]:
    print("retake")
else:
    print("Fail")

retake


In [64]:
range(5)

range(0, 5)

In [65]:
list(range(5))

[0, 1, 2, 3, 4]

In [72]:
list(range(2, 5))

[2, 3, 4]

In [67]:
for n in range(3):
    print(n)

0
1
2


In [70]:
for k in range(4):
    print(k * 2)

0
2
4
6


In [71]:
from tqdm.notebook import tqdm
import time

for char in tqdm(["a", "b", "c", "d"]):
    print(char)
    time.sleep(2)

  0%|          | 0/4 [00:00<?, ?it/s]

a
b
c
d


In [73]:
a = [2 ,6, 7, 8, 9]
listt = [num for num in a if num % 2 == 0]
listt

[2, 6, 8]

In [76]:
a = [2, 6, 7, 8, 9]
listt = []
for num in a:
    if num % 2 == 0:
        listt = listt + [num]
listt

[2, 6, 8]

In [77]:
def udf_01(a):
    print(a)

In [78]:
udf_01()

TypeError: udf_01() missing 1 required positional argument: 'a'

In [79]:
udf_01(100)

100


In [80]:
def udf_02(aa = 2):
    print(aa)

In [82]:
udf_02()

2


In [83]:
udf_02(aa = 100)

100


In [84]:
def udf_03(aa, bb):
    print(aa)
    print(bb)
udf_03()

TypeError: udf_03() missing 2 required positional arguments: 'aa' and 'bb'

In [86]:
udf_03(aa = 100)

TypeError: udf_03() missing 1 required positional argument: 'bb'

In [87]:
udf_03(aa = 100, bb = 200)

100
200


In [85]:
def udf_04(aa, bb):
    return aa + bb
udf_04(aa = 100, bb = 200)
udf_result = udf_04(aa = 100, bb = 200)
udf_result

300

In [88]:
a = [1,3,4,5]
def udf_mean(a):
    return sum(a)/len(a)
print(udf_mean(a))

3.25


In [92]:
def udf_mean(a):
    result = sum(a)/len(a)
    return result
print(udf_mean(a))

3.25


In [93]:
!pip install pandas --user

In [98]:
import numpy as np

In [99]:
np.array([2,4,6])

array([2, 4, 6])

In [100]:
arr = np.array([2,4,6])
arr

array([2, 4, 6])

In [101]:
arr + 2

array([4, 6, 8])

In [102]:
arr * 4

array([ 8, 16, 24])

In [104]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
arr_sub = arr[0, 0:2]
arr_sub

array([1, 2])

In [106]:
arr[0, 0:2] = [99, 88]
arr

array([[99, 88,  3],
       [ 4,  5,  6]])

In [107]:
arr_sub

array([99, 88])

In [167]:
np.random.seed(123)
np_rnorm = np.random.normal(loc = 2, scale = 2,
                           size = 100)
print(np_rnorm.mean())
print(np_rnorm.std())

2.0542181469807193
2.256480940955922


In [140]:
np_rnorm = np.random.normal(loc = 2, scale = 2,
                           size = 100)
print(np_rnorm.mean())
print(np_rnorm.std())

2.2616959052565035
2.108533340284954


In [168]:
print(np.random.normal.__doc__)


        normal(loc=0.0, scale=1.0, size=None)

        Draw random samples from a normal (Gaussian) distribution.

        The probability density function of the normal distribution, first
        derived by De Moivre and 200 years later by both Gauss and Laplace
        independently [2]_, is often called the bell curve because of
        its characteristic shape (see the example below).

        The normal distributions occurs often in nature.  For example, it
        describes the commonly occurring distribution of samples influenced
        by a large number of tiny, random disturbances, each with its own
        unique distribution [2]_.

        .. note::
            New code should use the ``normal`` method of a ``default_rng()``
            instance instead; please see the :ref:`random-quick-start`.

        Parameters
        ----------
        loc : float or array_like of floats
            Mean ("centre") of the distribution.
        scale : float or array_like of floats
 

In [169]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [174]:
arr >= 3

array([False, False,  True,  True,  True])

In [173]:
np.where(arr >=3, 1, 0)

array([0, 0, 1, 1, 1])

In [175]:
import pandas as pd

In [177]:
ser = pd.Series([2,4,6,8])
ser

0    2
1    4
2    6
3    8
dtype: int64

In [178]:
ser.values

array([2, 4, 6, 8])

In [179]:
ser.index

RangeIndex(start=0, stop=4, step=1)

In [181]:
ser[0]

2

In [182]:
ser[:3]

0    2
1    4
2    6
dtype: int64

In [183]:
ser[-2:]

2    6
3    8
dtype: int64

In [184]:
ser[ser != 4]

0    2
2    6
3    8
dtype: int64

In [185]:
ser[ser > 2]

1    4
2    6
3    8
dtype: int64

In [186]:
ser * 2

0     4
1     8
2    12
3    16
dtype: int64

In [187]:
ser.max()

8

In [189]:
ser.min()

2

In [190]:
ser.mean()

5.0

In [191]:
ser.idxmax()

3

In [192]:
ser.idxmin()

0

In [193]:
ser.astype('str')

0    2
1    4
2    6
3    8
dtype: object

In [195]:
ser.astype('str') + "월"

0    2월
1    4월
2    6월
3    8월
dtype: object

In [196]:
ser.reset_index()

index  0
0      0  2
1      1  4
2      2  6
3      3  8

In [197]:
ser.reset_index(drop = True)

0    2
1    4
2    6
3    8
dtype: int64

In [206]:
pd.DataFrame({"aa": [1,2,3],
            "bb": ["a", "b"]})

ValueError: arrays must all be same length

In [207]:
df = pd.DataFrame({"aa":[1,2,3],
                  "bb": ["a", "b", "c"]})
df

aa bb
0   1  a
1   2  b
2   3  c

In [202]:
df.columns

Index(['aa', 'bb'], dtype='object')

In [203]:
df.shape

(3, 2)

In [204]:
len(df)

3

In [208]:
df.aa

0    1
1    2
2    3
Name: aa, dtype: int64

In [209]:
df["aa"]

0    1
1    2
2    3
Name: aa, dtype: int64

In [210]:
df.loc[:, "aa"]

0    1
1    2
2    3
Name: aa, dtype: int64

In [211]:
df.iloc[:, 0]

0    1
1    2
2    3
Name: aa, dtype: int64

In [212]:
df.loc[:1,]

aa bb
0   1  a
1   2  b

In [213]:
df.iloc[:1,]

aa bb
0   1  a

In [214]:
df.iloc[0,]

aa    1
bb    a
Name: 0, dtype: object

In [215]:
df.iloc[[0], ]

aa bb
0   1  a

In [219]:
df2 = pd.DataFrame([[1,2], [3,4]],
             columns = ["a", "b"])
df2

a  b
0  1  2
1  3  4

In [220]:
df

aa bb
0   1  a
1   2  b
2   3  c

In [221]:
df.columns

Index(['aa', 'bb'], dtype='object')

In [222]:
df.columns[1]

'bb'

In [224]:
df.columns = ["xx", "yy"]

In [225]:
df.columns

Index(['xx', 'yy'], dtype='object')

In [229]:
df = df.rename(columns = {"xx": "obs"})
df

obs yy
0    1  a
1    2  b
2    3  c

In [233]:
df.to_csv("write_index_True.csv")
df.to_csv("write_index_False.csv", index = False)

In [234]:
pd.read_csv("write_index_True.csv")

Unnamed: 0  obs yy
0           0    1  a
1           1    2  b
2           2    3  c

In [235]:
pd.read_csv("write_index_False.csv")

obs yy
0    1  a
1    2  b
2    3  c

In [236]:
import os
os.getcwd()

'/Users/parkdonghyeok/Desktop/ProDS_파이썬 실기 특강'

In [237]:
os.listdir()

['write_index_False.csv',
 'ProDS_실기특강_2021.10.25.ipynb',
 '.ipynb_checkpoints',
 'write_index_True.csv']

In [240]:
os.listdir("car")

['vauxhall.csv',
 'bmw.csv',
 'unclean cclass.csv',
 'vw.csv',
 'hyundi.csv',
 'audi.csv',
 'unclean focus.csv',
 'toyota.csv',
 'ford.csv',
 'focus.csv',
 'skoda.csv',
 'cclass.csv',
 'merc.csv']

In [241]:
folder = "car"
list_files = os.listdir(folder)

df_bind = pd.DataFrame()
for file in list_files:
    file_path = folder + "/" + file
    df_sub = pd.read_csv(file_path)
    print(len(df_sub))
    df_bind = pd.concat([df_bind, df_sub])
    
len(df_bind)

13632
10781
4006
15157
4860
10668
5604
6738
17965
5454
6267
3899
13119


118150